### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by rgomez90** [PromoFaux/Matterhook.NET.MatterhookClient#11]
This repo needs some tests to assure it works as wished 😄

**Comment by PromoFaux** [comment]
Very agree with that. I'm a terrible dev insofar as I never learned to write testable code! All a bit "new fangled" for my experience ;) this project feels like a good fit to start learning, however :)

**Comment by cindra10** [comment]
Hi everyone, 
I would like to give this a shot.
Would it be ok to provide a webhook URL from the app.config since the webhook endpoint should be kept secret?
Are there any specific cases you would like to be covered?

**Comment by PromoFaux** [comment]
Feel free to give it a shot! I think I could probably stand to learn a thing or two myself.

RE: Webhook URL. That raises an interesting point. In order to test this library, are we going to need an available endpoint for it to ping? I would have thought the tests would need to be self-contained, and not rely on a (potentially unavailable) external source.

Then again, I have no idea what I'm talking about when it comes to tests so... 🤷‍♂️

**Comment by cindra10** [comment]
Tests should be mocked but I've never done any HTTP related testing and this was the first idea I've had. I could do some research on this topic later today.

**Comment by PromoFaux** [comment]
Just going to drop this here to remember to read it later:

https://github.com/WireMock-Net/WireMock.Net

**Comment by fluffynuts** [comment]
@cindra10 if you can inject a url for the endpoints you want to hit, check out nuget package [PeanutButter.SimpleHttpServer](https://www.nuget.org/packages/PeanutButter.SimpleHttpServer) -- check out the tests [here](https://github.com/fluffynuts/PeanutButter/blob/b04ecd02313ea81bcce0dad0549df43cd27d6a05/source/SimpleServers/PeanutButter.SimpleHTTPServer.Tests/TestHttpServer.cs#L82) for usage. Happy hacking (:

**Comment by rgomez90** [comment]
@PromoFaux , @cindra10 AFAIK unit tests SHOULD be self-contained. You should not hit any real endpoint in unit tests, that's the case for integration tests. I never tested http methods, but I heard about mocking `HttpMessageHandler`.

**Comment by rgomez90** [comment]
After reading a while, a possible solution would be to mock (using Moq) `HttpMessageHandler` to return a  `OK` response that contains the json we sent. This way we could test if the json looks like it should. 

Here the [article](https://gingter.org/2018/07/26/how-to-mock-httpclient-in-your-net-c-unit-tests/)

**Comment by cindra10** [comment]
@rgomez90 You are correct, I was too tired when I initialy responded to this so we can kind of ignore previous replies 😄. I've taken a look at both proposed packages (by @PromoFaux  and @fluffynuts), both are relatively easy to setup . Other than that I didn't have much time to investigate, I will take a look at the article you linked ASAP.

**Comment by rgomez90** [comment]
hey @cindra10 😄 are you working / gonna work on it at the end?

**Comment by cindra10** [comment]
Hi @rgomez90 sorry but I simply can't find time to work on anything currently, college and work are just taking too much effort 😞. Since I'd still like to learn a few things about testing HTTP related projects, could you please let me know when these are implemented so I can take a look? :)

**Comment by rgomez90** [comment]
First goes first @cindra10!! Thanks for the quick response! 😄 Sure! We'll let you know once implemented!
