### ISSUE TITLE
appveyor yaml appending -dev to tagged version

### ISSUE THREAD

**Issue by PromoFaux** [PromoFaux/Matterhook.NET.MatterhookClient#21]
This has had the unfortunate side-effect of the 1.4 release in nuget being named wrong

Only cosmetic, but could be confusing to folk downloading the package from nuget.

Would like to get it fixed before 1.5 (or perhaps release a 1.4.1)

![image](https://user-images.githubusercontent.com/1998970/47722263-e6573b80-dc49-11e8-9c4a-ca708dbb980a.png)

**Comment by PromoFaux** [comment]
Also to note, I'd rather the build number wasn't in the package version.

**Comment by rgomez90** [comment]
@PromoFaux I saw it as well in CI console when you merged. Issue appears to be in the If...Else. (Maybe `{branch}` is not "recognized" by cmd....

I think we could open a gitter channel to have a place to speak in "real time" and for any user. If you agree I'll open one.

**Comment by PromoFaux** [comment]
https://gitter.im/Promofaux/Matterhook.NET.MatterhookClient
