### ISSUE TITLE
Feature Interactive Message Buttons

### ISSUE THREAD

**Issue by rgomez90** [PromoFaux/Matterhook.NET.MatterhookClient#4]
I was thinking to implement it in my app, which use this library. Are there some plans about it, or should I make a PR if I ended implementing it?

**Comment by PromoFaux** [comment]
I'll gladly accept a PR if you end up implementing! I do need to sit down and go through things at some point, but been very busy in "real life" of late, so just haven't had time!

**Comment by PromoFaux** [comment]
@rgomez90 did you ever come up with anything on this?

**Comment by rgomez90** [comment]
@PromoFaux I didn't try it at all for now. I was busy with the core of a big project (where I plan to use interactive buttons) but haven't had the time for it. 

I hope I give it a try in the next days since I have a bit more time at the moment

**Comment by rgomez90** [comment]
Hi @PromoFaux I finally implemented int, buttons. Will make a few tests and will make a PR when finished :)

**Comment by PromoFaux** [comment]
Great stuff! Looking forward to seeing it :)

**Comment by rgomez90** [comment]
**Done! See #9.** (Not building in AppVeyor...)
Plaease, take a look & review. 

Today I notice there are now alos **Menu buttons** and the option to "create lists from users etc" (if I understood it right) in the interactive buttons. See [link](https://docs.mattermost.com/developer/interactive-messages.html#message-buttons). When Pr merged will work on that.

**Comment by PromoFaux** [comment]
Will close this after I release the next version. Probably 1.4 as we've added a new feature

**Comment by rgomez90** [comment]
Great! 😄  Would you agree a milestone for **v1.0.4** with interactive buttons and message menus support? So we could release soon, and for 1.0.5 (or 2.0) milestone should be text parsing?
